server:
  port: 8081
  servlet:
    context-path: /addressbook
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
    hikari:
      pool-name: AddressBookCP
      maximum-pool-size: 10
      connection-timeout: 20000
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: build/schema.sql

springdoc:
  swagger-ui:
    path: /swagger-ui.html