spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
    hikari:
      pool-name: AddressBookCP
      maximum-pool-size: 10
      connection-timeout: 20000