version: "3.9"

services:
  app:
    image: address_book
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - '8080:8080'
    links:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'